#-------------git---------------------------------------------------->>>
alias ga="git add ."
alias gb="git branch -a"
alias gbd="git branch -d"
alias gbod="git push origin --delete";
alias gc="git commit -S -m "
alias gd="git diff"
alias gs="git status"
alias gdh="git diff HEAD"
alias gp="git push"
alias gpu="git pull"
alias gpt="git push -u origin trunk"
alias gph="git push -u origin HEAD"
alias gsl="git stash list"
alias gsf="git stash push --"
alias gsp="git stash pop"
alias gco="git checkout"
alias gcob="git checkout -b"
alias gcot="git checkout trunk"
#-------------end-of-line------------------------------------------->>>
